version: "3.8"
services:
  rest-api:
    container_name: rest-api
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    image: emotion-api
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - "8080:80"           # ahora NGINX escucha en el host por el 8080
    depends_on:
      - rest-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9091:9090"         # si el 9090 te chocaba, ya lo cambiaste
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"         # Grafana en host Puerto 3001
    restart: unless-stopped


