version: "3.8"
services:
  rest-api:
    container_name: rest-api
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    image: emotion-api
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - "8080:80"           # NGINX expone el 80 interno en el 8080 del host
    depends_on:
      - rest-api
    volumes:
      - ./nginx/nginx.config:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9091:9090"         # prom en 9091 del host
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"         # grafana en 3001 del host
    restart: unless-stopped
