version: "3.8"
services:
  rest-api:
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    image: emotion-api
    ports:
      - "8000:8000"

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    depends_on:
      - rest-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
